local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")
local kr_entities_icons_path = "__trigonometric-oil__/graphics/k2/icons/entities/"
local kr_entities_path = "__trigonometric-oil__/graphics/k2/entities/"

data:extend({
  {
    type = "assembling-machine",
    name = "fuel-refinery",
    icon = kr_entities_icons_path .. "fuel-refinery.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { hardness = 0.5, mining_time = 0.5, result = "fuel-refinery" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box = { { -1.5, -1.9 }, { 1.5, 1.5 } },
    module_specification = { module_slots = 3 },
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    animation = make_4way_animation_from_spritesheet({
      layers = {
        {
          filename = kr_entities_path .. "fuel-refinery/fuel-refinery.png",
          width = 122,
          height = 134,
          frame_count = 1,
          shift = util.by_pixel(-5, -4.5),
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-fuel-refinery.png",
            width = 244,
            height = 268,
            frame_count = 1,
            shift = util.by_pixel(-5, -4.5),
            scale = 0.5,
          },
        },
        {
          filename = kr_entities_path .. "fuel-refinery/fuel-refinery-shadow.png",
          width = 156,
          height = 141,
          frame_count = 1,
          shift = util.by_pixel(31.5, 11),
          draw_as_shadow = true,
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-fuel-refinery-shadow.png",
            width = 350,
            height = 219,
            frame_count = 1,
            shift = util.by_pixel(31.5, 10.75),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    }),
    working_visualisations = {
      {
        north_position = util.by_pixel(30, -24),
        west_position = util.by_pixel(1, -49.5),
        south_position = util.by_pixel(-30, -48),
        east_position = util.by_pixel(-11, -1),
        apply_recipe_tint = "primary",
        animation = {
          filename = kr_entities_path .. "fuel-refinery/boiling-green-patch.png",
          frame_count = 32,
          width = 15,
          height = 10,
          animation_speed = 0.5,
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-boiling-green-patch.png",
            frame_count = 32,
            width = 30,
            height = 20,
            animation_speed = 0.5,
            scale = 0.5,
          },
        },
      },
      {
        north_position = util.by_pixel(30, -24),
        west_position = util.by_pixel(1, -49.5),
        south_position = util.by_pixel(-30, -48),
        east_position = util.by_pixel(-11, -1),
        apply_recipe_tint = "secondary",
        animation = {
          filename = kr_entities_path .. "fuel-refinery/boiling-green-patch-mask.png",
          frame_count = 32,
          width = 15,
          height = 10,
          animation_speed = 0.5,
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-boiling-green-patch-mask.png",
            frame_count = 32,
            width = 30,
            height = 20,
            animation_speed = 0.5,
            scale = 0.5,
          },
        },
      },
      {
        apply_recipe_tint = "tertiary",
        north_position = { 0, 0 },
        west_position = { 0, 0 },
        south_position = { 0, 0 },
        east_position = { 0, 0 },
        north_animation = {
          filename = kr_entities_path .. "fuel-refinery/boiling-window-green-patch.png",
          frame_count = 1,
          width = 87,
          height = 60,
          shift = util.by_pixel(0, -5),
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-boiling-window-green-patch.png",
            x = 0,
            frame_count = 1,
            width = 174,
            height = 119,
            shift = util.by_pixel(0, -5.25),
            scale = 0.5,
          },
        },
        east_animation = {
          filename = kr_entities_path .. "fuel-refinery/boiling-window-green-patch.png",
          x = 87,
          frame_count = 1,
          width = 87,
          height = 60,
          shift = util.by_pixel(0, -5),
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-boiling-window-green-patch.png",
            x = 174,
            frame_count = 1,
            width = 174,
            height = 119,
            shift = util.by_pixel(0, -5.25),
            scale = 0.5,
          },
        },
        south_animation = {
          filename = kr_entities_path .. "fuel-refinery/boiling-window-green-patch.png",
          x = 174,
          frame_count = 1,
          width = 87,
          height = 60,
          shift = util.by_pixel(0, -5),
          hr_version = {
            filename = kr_entities_path .. "fuel-refinery/hr-boiling-window-green-patch.png",
            x = 348,
            frame_count = 1,
            width = 174,
            height = 119,
            shift = util.by_pixel(0, -5.25),
            scale = 0.5,
          },
        },
      },
    },

    water_reflection = {
      pictures = {
        filename = kr_entities_path .. "fuel-refinery/fuel-refinery-reflection.png",
        priority = "extra-high",
        width = 44,
        height = 44,
        shift = util.by_pixel(0, 40),
        variation_count = 1,
        scale = 5,
      },
      rotate = false,
      orientation_to_variation = false,
    },

    vehicle_impact_sound = sounds.generic_impact,
    working_sound = {
      sound = {
        filename = "__trigonometric-oil__/sounds/advanced-chemical-plant.ogg",
        volume = 0.7,
      },
      idle_sound = {
        filename = "__base__/sound/idle1.ogg",
        volume = 0.6,
      },
      apparent_volume = 1.5,
    },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = 10,
    },
    energy_usage = "250kW",
    ingredient_count = 4,
    crafting_categories = { "special-oil" },
    fluid_boxes = {
      -- Inputs
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = -1,
        pipe_connections = { { type = "input", position = { -1, -2 } } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = -1,
        pipe_connections = { { type = "input", position = { 1, -2 } } },
      },
      -- Outputs
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        base_level = 1,
        pipe_connections = { { position = { -1, 2 } } },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        base_level = 1,
        pipe_connections = { { position = { 1, 2 } } },
      },
    },
  },
})

local animation = {
  layers = {
    {
      filename = kr_entities_path .. "gas-power-station/gas-power-station.png",
      width = 190,
      height = 190,
      frame_count = 32,
      line_length = 8,
      animation_speed = 1.2,
      shift = { 0, 0 },
      hr_version = {
        filename = kr_entities_path .. "gas-power-station/hr-gas-power-station.png",
        width = 380,
        height = 380,
        scale = 0.5,
        frame_count = 32,
        line_length = 8,
        animation_speed = 1.2,
        shift = { 0, 0 },
      },
    },
    {
      filename = kr_entities_path .. "pipe-patch/pipe-patch.png",
      width = 28,
      height = 25,
      frame_count = 1,
      repeat_count = 32,
      shift = { 0, 2.5 },
      hr_version = {
        filename = kr_entities_path .. "pipe-patch/hr-pipe-patch.png",
        width = 55,
        height = 50,
        frame_count = 1,
        repeat_count = 32,
        scale = 0.5,
        shift = { 0, 2.5 },
      },
    },

    {
      filename = kr_entities_path .. "gas-power-station/gas-power-station-sh.png",
      width = 190,
      height = 190,
      frame_count = 1,
      repeat_count = 32,
      animation_speed = 1.2,
      draw_as_shadow = true,
      shift = { 0, 0 },
      hr_version = {
        filename = kr_entities_path .. "gas-power-station/hr-gas-power-station-sh.png",
        width = 380,
        height = 380,
        scale = 0.5,
        frame_count = 1,
        repeat_count = 32,
        animation_speed = 1.2,
        draw_as_shadow = true,
        shift = { 0, 0 },
      },
    },
  },
}

data:extend({
  {
    type = "trivial-smoke",
    name = "gas-power-station-smoke",
    duration = 300,
    fade_in_duration = 0,
    fade_away_duration = 180,
    spread_duration = 400,
    start_scale = 0.17,
    end_scale = 1.15,
    color = { r = 0.25, g = 0.25, b = 0.25, a = 0.75 },
    cyclic = true,
    affected_by_wind = true,
    animation = {
      width = 152,
      height = 120,
      line_length = 5,
      frame_count = 60,
      shift = { -0.53125, -0.4375 },
      priority = "high",
      animation_speed = 0.25,
      filename = "__base__/graphics/entity/smoke/smoke.png", --kr_entities_path .. "gas-power-station/gas-power-station-smoke.png",
      flags = { "smoke" },
    },
  },
  {
    type = "generator",
    name = "gas-power-station",
    icon = kr_entities_icons_path .. "gas-power-station.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "gas-power-station" },
    max_health = 750,
    corpse = "oil-refinery-remnants",
    dying_explosion = "medium-explosion",
    fluid_usage_per_tick = 0.16666666667,
    maximum_temperature = 25,
    burns_fluid = true,
    scale_fluid_usage = true,
    destroy_non_fuel_fluid = false,
    effectivity = 1,
    resistances = {
      { type = "physical", percent = 25 },
      { type = "fire", percent = 75 },
      { type = "impact", percent = 50 },
    },
    collision_box = { { -2.3, -2.3 }, { 2.3, 2.3 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    damaged_trigger_effect = hit_effects.entity(),
    fluid_box = {
      pipe_covers = pipecoverspictures(),
      pipe_picture = kr_pipe_path,
      off_when_no_fluid_recipe = false,
      base_area = 1,
      height = 2,
      base_level = -1,
      pipe_connections = {
        { type = "input-output", position = { 3, 0 } },
        { type = "input-output", position = { -3, 0 } },
        { type = "input-output", position = { 0, 3 } },
        { type = "input-output", position = { 0, -3 } },
      },
      production_type = "input-output",
      minimum_temperature = 25.0,
    },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-output",
      emissions_per_minute = 10,
    },
    horizontal_animation = animation,
    vertical_animation = animation,
    smoke = {
      {
        name = "gas-power-station-smoke",
        north_position = util.by_pixel(47, -88),
        south_position = util.by_pixel(47, -88),
        east_position = util.by_pixel(47, -88),
        west_position = util.by_pixel(47, -88),
        frequency = 0.350,
        starting_vertical_speed = 0.05,
        slow_down_factor = 1,
        starting_frame_deviation = 60,
      },
    },
    vehicle_impact_sound = {
      filename = "__base__/sound/car-metal-impact.ogg",
      volume = 0.65,
    },
    working_sound = {
      sound = {
        variations = {
          {
            filename = "__trigonometric-oil__/sounds/gas-power-station-1.ogg",
            volume = 0.8,
          },
          {
            filename = "__trigonometric-oil__/sounds/gas-power-station-2.ogg",
            volume = 0.75,
          },
        },
        aggregation = {
          max_count = 3,
          remove = false,
          count_already_playing = true,
        },
      },
      match_speed_to_activity = true,
      max_sounds_per_type = 3,
      fade_in_ticks = 10,
      fade_out_ticks = 30,
    },

    water_reflection = {
      pictures = {
        filename = kr_entities_path .. "gas-power-station/gas-power-station-reflection.png",
        priority = "extra-high",
        width = 42,
        height = 38,
        shift = util.by_pixel(0, 40),
        variation_count = 1,
        scale = 5,
      },
      rotate = false,
      orientation_to_variation = false,
    },

    audible_distance_modifier = 5,
    min_perceived_performance = 0.25,
    performance_to_sound_speedup = 0.5,
    max_power_output = "4000KW",
  },
})
